config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :bookings
  devise_for :users
  resources :users
  resources :books
  root to: 'home#index'
  get 'home', to: 'home#index'
  delete '/books/:id', to: 'books#destroy'


#  get "/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :isbn, presence: true
  validates :year, presence: true
  validates :editorial, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :book_id, presence: true
  validates :user_dni, presence: true, length: { minimum: 6 }
  validates :start_booking, presence: true
  validates :start_date, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Reserva/prestamo creada." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Reserva/prestamo actualizada." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Reserva/prestamo eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:book_id, :user_dni, :start_booking, :start_date, :end_time, :state)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Libro cargado." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Libro actualizado." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :isbn, :year, :editorial, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find_by(id: params[:id])
     if @user.nil?
        redirect_to users_path
     end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Usuario creado." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Cambios en el usuario aplicados correctamente." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :dni, :phone, :email, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/edit.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <main class="container" role="main">
      <div class="jumbotron">
        <p class="lead">Bienvenido</p>
      </div>
<h1>Editar libro</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Volver a Lista de Reservas', bookings_path %>

app/views/bookings/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <main class="container" role="main">
      <div class="jumbotron">
        <p class="lead">Bienvenido</p>
        <a class="btn btn-lg btn-primary" href="https://isfdyt210-bue.infd.edu.ar/sitio/" target="_blank" role="button">Ir a Instituto 210 &raquo;</a>
        <br>
      </div>

<h1>Lista de reservas</h1>

<table class="table table-responsive table-striped">
    <thead>
      <tr>
        <th>ISBN del Libro</th>
        <th>DNI del solicitante</th>
        <th>Reserva creada el</th>
        <th>Fecha desde</th>
        <th>Fecha hasta</th>
        <th>Estado de la reserva</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.book_id %></td>
          <td><%= booking.user_dni %></td>
          <td><%= booking.start_booking %></td>
          <td><%= booking.start_date %></td>
          <td><%= booking.end_time %></td>
          <td><%= booking.state %></td>
          <% if current_user && current_user.role == "Bibliotecario" %>
          <td><%= link_to 'Editar', edit_booking_path(booking), class: "btn btn-secondary btn-user active" %></td>
            <td><%= button_to 'Eliminar', booking, method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger btn-user active"%></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
</table>



<%= link_to 'Nueva reserva', new_booking_path %>
<br>
<%= link_to 'Lista de libros', books_path %>
<br>
<% if current_user && current_user.role == "Bibliotecario" %>
<%= link_to 'Lista de usuarios', users_path %>
<% end %>

app/views/bookings/new.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
  <%= csrf_meta_tag %>
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>
<br>
<br>


<h1>Generar una nueva reserva</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Atras', bookings_path %>

app/views/bookings/show.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
  <%= csrf_meta_tag %>
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>
<br>
<br>
<p>
  <strong>ISBN del libro:</strong>
  <%= @booking.book_id %>
</p>

<p>
  <strong>DNI:</strong>
  <%= @booking.user_dni %>
</p>

<p>
  <strong>Fecha de reserva:</strong>
  <%= @booking.start_booking %>
</p>

<p>
  <strong>Fecha desde:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>Fecha hasta:</strong>
  <%= @booking.end_time %>
</p>

<p>
  <strong>State:</strong>
  <%= @booking.state %>
</p>

<%= link_to 'Editar reserva', edit_booking_path(@booking) %> |
<%= link_to 'Ir a lista de reservas', bookings_path %>

app/views/books/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
  <%= csrf_meta_tag %>
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <main class="container" role="main">
      <div class="jumbotron">
        <p class="lead">Bienvenido</p>
        <a class="btn btn-lg btn-primary" href="https://isfdyt210-bue.infd.edu.ar/sitio/" target="_blank" role="button">Ir a Instituto 210 &raquo;</a>
        <br>
      </div>



<h1>Libros</h1>

<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>ISBN</th>
      <th>Año</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.isbn %></td>
        <td><%= book.year %></td>
        <td><%= book.author %></td>
        <td><%= book.editorial %></td>
        <% if current_user && current_user.role == "Bibliotecario" %>
        <td><%= link_to 'Editar', edit_book_path(book), class: "btn btn-secondary active" %></td>
        <td><%= button_to 'Eliminar', book, method: :delete, data: { confirm: 'Desea eliminar este libro?'}, class: "btn btn-danger btn-user active"  %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.role == "Bibliotecario" %>

<%= link_to 'Nuevo libro', new_book_path %>
<br>

<%= link_to 'Lista de usuarios', users_path %>
<% end %>
<br>
<%= link_to 'Lista de reservas', bookings_path %>

app/views/books/show.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

<br>
<br>
<br>

<p>
  <strong>Nombre:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Año:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @book.editorial %>
</p>

<%= link_to 'Editar', edit_book_path(@book) %> |
<%= link_to 'Volver al indice', books_path %>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>
          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <main class="container" role="main">
      <div class="jumbotron">
        <p class="lead">Bienvenido</p>
        <a class="btn btn-lg btn-primary" href="https://isfdyt210-bue.infd.edu.ar/sitio/" target="_blank" role="button">Ir a Instituto 210 &raquo;</a>
        <br>
      </div>

      <div class="container"></div>
      <br>
      <p class="lead">Bienvenido a la Biblioteca Virtual</p>
      <% if current_user%>
      <div class="row"><div class="col-md-4"><h2><%=link_to 'Ver libros del Instituto', books_path%></h2><p>Aqui se puede visualizar el catalogo completo de los libros que dispone la biblioteca de Instituto.<a href="http://localhost:3000/books" target="_blank"><img class="img-fluid mt-3" src="https://okdiario.com/img/2018/04/23/bibliosmia--adoras-el-olor-a-libros-viejos-2.jpg"></a></p></div>
      <div class="col-md-4"><h2><%= link_to 'Realizar una reserva', new_booking_path %></h2><p>En esta seccion usted podra reservar un libro  .<a href="http://localhost:3000/bookings/new" target="_blank"><img class="img-fluid mt-2" src="https://images-na.ssl-images-amazon.com/images/I/71tlSeUFAyL._AC_SL1500_.jpg"></a></p></div>
      <div class="col-md-4"><h2><%= link_to 'Lista de reservas', bookings_path %></h2><p>Al ingresar a este apartado podra ver las reservas generadas por los distintos usuarios del Instituto<a href="http://localhost:3000/bookings" target="_blank"><img class="img-fluid mt-2" src="http://factorypyme.thestandardit.com/wp-content/uploads/sites/5/2016/05/Agenda-las-5.jpg"></a></p></div>
      <% end %>

      <% if current_user && current_user.role == "Bibliotecario" %>
      <div class="row justify-content-center"><div class="col-md-4"><h2><%= link_to 'Lista de usuarios', users_path %></h2><p>Seccion para administrador. Se encarga de la gestion de usuarios que se registran en la plataforma.<a href="http://localhost:3000/users" target="_blank"><img class="img-fluid mt-3" src="https://previews.123rf.com/images/cienpies/cienpies1211/cienpies121100002/16307604-personas-diversidad-de-usuarios-conectados-a-las-redes-sociales-de-fondo-sin-fisuras-patr%C3%B3n-en-el-estil.jpg"></a></p></div>

      <% end %>
    <footer></footer><div class="container"><div align="center">Desarrollado por <a href="https://gitlab.com/BracIvan" target="_blank">Ivan Brac</a></div></div>

    <br><br>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <main class="container" role="main">
      <div class="jumbotron">
        <p class="lead">Bienvenido</p>
        <a class="btn btn-lg btn-primary" href="https://isfdyt210-bue.infd.edu.ar/sitio/" target="_blank" role="button">Ir a Instituto 210 &raquo;</a>
        <br>
      </div>

<h1>Usuarios</h1>
<h6> Si usted no tiene permisos de Bibliotecario no visualizara ningun usuario registrado </h6>
  <% if current_user && current_user.role == "Bibliotecario" %>
<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dni</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.dni %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Editar', edit_user_path(user), class: "btn btn-secondary active" %></td>
        <td><%= button_to 'Eliminar', user, method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger btn-user active" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<br>
<%= link_to 'Lista de libros', books_path %>
<br>
<%= link_to 'Lista de reservas', bookings_path %>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
      <a class="navbar-brand" href="http://localhost:3000/">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <ul class="nav navbar-top-links navbar-right">
            <% unless current_user.present? %>
              <li {padding-bottom: 2px;}>
                 <%=link_to 'Iniciar sesion', "http://localhost:3000/users/sign_in"%>
              </li>
              <ul>
                 <%=link_to 'Registrarse', "http://localhost:3000/users/sign_up"%>
              </ul>
            <%end%>
            <% if current_user.present? %>
              <li{padding-bottom: 2px;}>
                 <%= link_to 'Cerrar sesion', destroy_user_session_path, :method=>'delete' %>
              </li>
            <%end%>

          </ul>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>



<p>
  <strong>Nombre:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @user.dni %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Volver a Usuarios', users_path %>